name: Update

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 22 * * *

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install aligo

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p artifacts  # 创建一个目录用于存放打包后的文件
        git clone --depth=1 --branch=main https://github.com/hkpc/V2ray-Configs.git
        mv V2ray-Configs V2ray-Configs-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/V2ray-Configs-$(date +%Y%m%d).zip V2ray-Configs-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/hkpc/Autoproxy.git
        mv Autoproxy Autoproxy-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/Autoproxy-$(date +%Y%m%d).zip Autoproxy-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/hkpc/openit.git
        mv openit openit-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/openit-$(date +%Y%m%d).zip openit-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/hkpc/Configs.git
        mv Configs Configs-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/Configs-$(date +%Y%m%d).zip Configs-$(date +%Y%m%d)

    - name: Upload V2ray-Configs
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/V2ray-Configs* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/V2ray-Configs" --file "${zip_files}"

    - name: Upload Autoproxy
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/Autoproxy* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/Autoproxy" --file "${zip_files}"

    - name: Upload openit
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/openit* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/openit" --file "${zip_files}"

    - name: Upload Configs
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/Configs* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/Configs" --file "${zip_files}"
