name: Update

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 30 22 * * *

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install aligo

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p artifacts  # 创建一个目录用于存放打包后的文件
        git clone --depth=1 --branch=main https://github.com/rvvu/OpenWrt.git
        mv OpenWrt OpenWrt-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/OpenWrt-$(date +%Y%m%d).zip OpenWrt-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/rvvu/Toolbox.git
        mv Toolbox Toolbox-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/Toolbox-$(date +%Y%m%d).zip Toolbox-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/rvvu/kernel.git
        mv kernel kernel-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/kernel-$(date +%Y%m%d).zip kernel-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/rvvu/Autoproxy.git
        mv Autoproxy Autoproxy-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/Autoproxy-$(date +%Y%m%d).zip Autoproxy-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/rvvu/openit.git
        mv openit openit-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/openit-$(date +%Y%m%d).zip openit-$(date +%Y%m%d)
        git clone --depth=1 --branch=Files https://github.com/rvvu/IPTV.git
        mv IPTV IPTV-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/IPTV-$(date +%Y%m%d).zip IPTV-$(date +%Y%m%d)
        git clone --depth=1 --branch=main https://github.com/rvvu/javbus.git
        mv javbus javbus-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/javbus-$(date +%Y%m%d).zip javbus-$(date +%Y%m%d)
        git clone --depth=1 --branch=master https://github.com/rvvu/op-ipk.git
        mv op-ipk op-ipk-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/op-ipk-$(date +%Y%m%d).zip op-ipk-$(date +%Y%m%d)
        git clone --depth=1 --branch=master https://github.com/rvvu/openwrt-packages.git
        mv openwrt-packages openwrt-packages-$(date +%Y%m%d)
        zip -r $GITHUB_WORKSPACE/artifacts/openwrt-packages-$(date +%Y%m%d).zip openwrt-packages-$(date +%Y%m%d)

    - name: Upload OpenWrt
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/OpenWrt* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/OpenWrt" --file "${zip_files}"

    - name: Upload Toolbox
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/Toolbox* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/Toolbox" --file "${zip_files}"

    - name: Upload kernel
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/kernel* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/kernel" --file "${zip_files}"

    - name: Upload Autoproxy
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/Autoproxy* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/Autoproxy" --file "${zip_files}"

    - name: Upload openit
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/openit* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/openit" --file "${zip_files}"

    - name: Upload IPTV
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/IPTV* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/IPTV" --file "${zip_files}"

    - name: Upload javbus
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/javbus* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/javbus" --file "${zip_files}"

    - name: Upload op-ipk
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/op-ipk* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/op-ipk" --file "${zip_files}"

    - name: Upload openwrt-packages
      run: | 
        echo "请自动忽略META-INF文件夹。" > $GITHUB_WORKSPACE/artifacts/忽略META-INF文件夹.txt
        zip_files=$(find $GITHUB_WORKSPACE/artifacts/openwrt-packages* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/file/aliupload.py
        python $GITHUB_WORKSPACE/file/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "GitHub/openwrt-packages" --file "${zip_files}"
